import slugify from '../utils/slugify'

export default {
  title: "Works",
  name: 'work',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this project",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Index Number",
      description: "The number used to identify this project (0 prefixed below 10) - eg: '03'",
      name: "indexNumber",
      type: "string",
    },
    {
      title: "Project Reference Code",
      description: `The shorthand reference code that appears on index hover - eg: 'Sölden, AU—18'`,
      name: "referenceCode",
      type: "string",
    },
    {
      title: "Client",
      description: "The name of the project - eg: 'Gensler Architecture'",
      name: "client",
      type: "string",
    },
    {
      title: "Location",
      description: "The location of this project - eg: 'San Francisco'",
      name: "location",
      type: "string",
    },
    {
      title: "GPS Coordinates",
      description: `The GPS Coordinates of this project - eg: “37°46'09.3"N 122°23'20.5"W”`,
      name: "gps",
      type: "string",
    },
    {
      title: "Year",
      description: "The year this project took place - eg: '2020'",
      name: "year",
      type: "string",
    },
    {
      title: 'Home Carousel Image',
      name: 'homeCarouselImage',
      description: 'The image that is shown on the carousel when this project is featured on the home page',
      type: 'image',
      options: {
        hotspot: true
      },
      fields: [
        {
          name: 'caption',
          type: 'string',
          title: 'Image Alt Text (Recommended for SEO)',
          options: {
            isHighlighted: true // <-- make this field easily accessible
          }
        },
      ]
    },
    {
      title: 'Image Slides',
      name: 'imageSlides',
      description: 'The modular slides that will display this projects imagery',
      type: 'array',
      of: [{type: 'imageSlide', title: 'Image Slide'}],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  // preview: {
  //   select: {
  //     title: 'title'
  //   },
  //   prepare ({ title }) {
  //     return {
  //       title
  //     }
  //   }
  // }

  preview: {
    select: {
      title: 'title',
      index: 'indexNumber',
      media: 'imageSlides.0.images.0',
    },
    prepare: (selection) => {

      return {
        title: `${selection.index} - ${selection.title}`,
        media: selection.media
      }
    }
  }
}